
# Variability of measures
SELECT M.MEDL_MEAS_ID, M.MEDL_MEAS_DESC, ROUND(V.STDEV_SCORE, 2)
FROM V_MEDL_MEAS_VAR V, T_MEDL_MEAS M
WHERE V.MEDL_MEAS_ID = M.MEDL_MEAS_ID
AND M.MEDL_MEAS_ID NOT IN ("EDV", "MV", "ED_1b", "ED_2b", "OP_18b")
ORDER BY STDEV_SCORE DESC
;
