select MEDL_MEAS_ID, max(cast(raw_score as float))
from T_HOSP_MEDL_MEAS_SCORE
GROUP BY MEDL_MEAS_ID
HAVING max(cast(raw_score as float)) > 100 ;



# Variability of measures
SELECT M.MEDL_MEAS_ID, M.MEDL_MEAS_DESC, ROUND((V.STDEV_SCORE * V.STDEV_SCORE), 2)
FROM V_MEDL_MEAS_VAR V, T_MEDL_MEAS M
WHERE V.MEDL_MEAS_ID = M.MEDL_MEAS_ID
AND M.MEDL_MEAS_ID NOT IN ("ED_2b", "OP_18b", "OP_20", "OP_21", "OP_5", "OP_3b", "ED_1b")
ORDER BY STDEV_SCORE DESC
;
