#STATES WITH BEST CARE



# Create a care rating aggragation of all valid hospitals by state
CREATE OR REPLACE VIEW V_BEST_STATE
AS
SELECT H.HOSP_ST_CD, count(M.RAW_SCORE) as COUNT_SCORE,
ROUND(AVG(BASE_SCORE), 2) AS STATE_BASE_SCORE, 
ROUND(AVG(CONST_SCORE), 2) AS STATE_CONST_SCORE,
round(AVG((cast(M.RAW_SCORE as float) - VM.AVG_SCORE) / VM.STDEV_SCORE), 2) as STATE_AVG_SD_SCORE
FROM T_HOSP H, T_HOSP_MEDL_MEAS_SCORE M, V_MEDL_MEAS_VAR VM, V_VALID_HOSP VH
WHERE H.PROVR_ID = M.PROVR_ID
AND M.RAW_Score  <> 'Not Available'
AND M.MEDL_MEAS_ID = VM.MEDL_MEAS_ID
and M.MEDL_MEAS_ID NOT IN ("EDV", "MV", "ED_1b", "ED_2b", "OP_18b")
and substring(M.MEDL_MEAS_ID,1, 4) NOT IN ("MORT", "READ")
and H.PROVR_ID = VH.PROVR_ID
GROUP BY H.HOSP_ST_CD, H.BASE_SCORE, H.CONST_SCORE
;

# Find the best states
SELECT hosp_st_cd, STATE_BASE_SCORE, STATE_CONST_SCORE, STATE_AVG_SD_SCORE,
rank() OVER (ORDER BY STATE_AVG_SD_SCORE DESC)
FROM  V_BEST_STATE
LIMIT 10
;
