#STATES WITH BEST CARE
SELECT hosp_st_cd, ROUND(AVG(BASE_SCORE), 2) AS STATE_BASE_SCORE, 
ROUND(AVG(CONST_SCORE), 2) AS STATE_CONST_SCORE, 
ROUND(AVG(AVG_SCORE), 2) as STATE_AVG_SCORE, 
ROUND(AVG(AVG_SD_SCORE), 2) AS STATE_AVG_SD_SCORE
FROM V_BEST_CARE
GROUP BY hosp_st_cd
ORDER BY STATE_AVG_SD_SCORE DESC
LIMIT 10;